CREATE TABLE chapters(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    comic_id VARCHAR(36) NOT NULL,
    number INT NOT NULL,
    publish BOOL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comics_chapters FOREIGN KEY(comic_id) REFERENCES comics(id) ON DELETE CASCADE ON UPDATE CASCADE
);